import { access, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const webRoot=path.join(root,"web");const failures=[];
const expect=(condition,message)=>{if(!condition)failures.push(message)};
const index=await readFile(path.join(webRoot,"index.html"),"utf8");const styles=await readFile(path.join(webRoot,"styles.css"),"utf8");const script=await readFile(path.join(webRoot,"script.js"),"utf8");const headers=await readFile(path.join(webRoot,"_headers"),"utf8");
expect((index.match(/data-pane="transactions"/g)??[]).length===1,"index.html: transactions pane must be unique");
expect(/<html lang="vi"/i.test(index),"index.html: thiếu lang=vi");expect(/<meta name="viewport"/i.test(index),"index.html: thiếu viewport");expect((index.match(/<h1\b/gi)??[]).length===1,"index.html: phải có đúng một h1");expect(/<main\b/i.test(index),"index.html: thiếu main landmark");expect(/data-login-form/i.test(index),"index.html: thiếu form đăng nhập");expect(/<dialog\b/i.test(index),"index.html: thiếu dialog xác nhận");expect(/aria-live="polite"/i.test(index),"index.html: thiếu aria-live");expect(!/data-api-base|data-token/i.test(index),"index.html: không được yêu cầu API URL/token thủ công");expect(/data-users-body/i.test(index)&&/data-transactions-body/i.test(index),"index.html: thiếu màn hình quản trị dữ liệu");expect(!/<img(?![^>]*\balt=)[^>]*>/i.test(index),"index.html: có img thiếu alt");expect(!/javascript:/i.test(index),"index.html: javascript URL bị cấm");
expect(/AbortController/.test(script),"script.js: thiếu hủy request");expect(/showModal\(/.test(script)&&/\.close\(/.test(script),"script.js: thiếu luồng dialog");expect(!/localStorage|sessionStorage/.test(script),"script.js: không được lưu session/token trong web storage");expect(/\/v1\/admin\/session\/login/.test(script),"script.js: thiếu session login");expect(/X-CSRF-Token/.test(script),"script.js: thiếu CSRF token");expect(/\/v1\/admin\/analytics/.test(script)&&/\/v1\/admin\/users/.test(script)&&/\/v1\/admin\/transactions/.test(script),"script.js: thiếu API quản trị V2");expect(/prefers-reduced-motion/.test(styles),"styles.css: thiếu reduced-motion");expect(/backdrop-filter/.test(styles),"styles.css: thiếu visual system");expect(/Content-Security-Policy:/.test(headers)&&/X-Robots-Tag: noindex/i.test(headers),"_headers: thiếu security headers");
for(const reference of [...index.matchAll(/(?:href|src)="(\/[^\"]+)"/g)].map(match=>match[1])){const resource=reference.split("#")[0].split("?")[0];if(!resource||resource==="/")continue;const local=resource.startsWith("/admin/")?resource.slice(7):resource.slice(1);try{await access(path.join(webRoot,local))}catch{failures.push(`index.html: tài nguyên không tồn tại ${reference}`)}}
if(failures.length)throw new Error(`ADMIN PORTAL TEST FAIL\n- ${failures.join("\n- ")}`);console.log("ADMIN PORTAL TEST PASS: auth, CSRF, semantic, a11y và static inventory ok.");
