[CmdletBinding()]
param(
    [ValidateSet('Release')]
    [string] $Configuration = 'Release',
    [ValidateSet('win-x64')]
    [string] $RuntimeIdentifier = 'win-x64',
    [string] $Version = '1.0.0-local'
)

$ErrorActionPreference = 'Stop'
$repositoryRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$projectPath = Join-Path $repositoryRoot 'src/AuditionModStudio.App/AuditionModStudio.App.csproj'
$outputRoot = [IO.Path]::GetFullPath((Join-Path $repositoryRoot 'App'))

if (-not $outputRoot.StartsWith($repositoryRoot + [IO.Path]::DirectorySeparatorChar,
        [StringComparison]::OrdinalIgnoreCase)) {
    throw 'APP_OUTPUT_MUST_BE_UNDER_REPOSITORY_ROOT'
}

if (Test-Path -LiteralPath $outputRoot) {
    Remove-Item -LiteralPath $outputRoot -Recurse -Force
}

& dotnet publish $projectPath `
    --configuration $Configuration `
    --runtime $RuntimeIdentifier `
    --self-contained true `
    --output $outputRoot `
    -p:Platform=x64 `
    -p:PortableRelease=true `
    -p:Version=$Version `
    -p:InformationalVersion=$Version

if ($LASTEXITCODE -ne 0) {
    throw 'APP_PUBLISH_FAILED'
}

$entryPoint = Join-Path $outputRoot 'AuditionModStudio.App.exe'
if (-not (Test-Path -LiteralPath $entryPoint -PathType Leaf)) {
    throw 'APP_ENTRY_POINT_MISSING'
}

# Keep only the product locales. Other satellite folders are generated by the
# Windows App SDK and are not needed by this application.
$supportedLocales = @('vi-VN', 'en-us')
Get-ChildItem -LiteralPath $outputRoot -Directory -Force | Where-Object {
    $_.Name -match '^[a-z]{2,3}(-[A-Za-z0-9]+)+$' -and $_.Name -notin $supportedLocales
} | ForEach-Object {
    Remove-Item -LiteralPath $_.FullName -Recurse -Force
}

# WinUI's portable publish pipeline does not retain content assets by default.
# Copy this after locale cleanup because the window loads it through AppWindow.SetIcon().
$iconSource = Join-Path $repositoryRoot 'src\AuditionModStudio.App\Assets\AppIcon.ico'
$iconOutputDirectory = Join-Path $outputRoot 'Assets'
if (-not (Test-Path -LiteralPath $iconSource -PathType Leaf)) {
    throw 'APP_ICON_SOURCE_MISSING'
}
New-Item -ItemType Directory -Path $iconOutputDirectory -Force | Out-Null
Copy-Item -LiteralPath $iconSource -Destination (Join-Path $iconOutputDirectory 'AppIcon.ico') -Force

# PDB files are debug symbols and are not needed to launch the portable app.
Get-ChildItem -LiteralPath $outputRoot -File -Recurse -Filter '*.pdb' -Force |
    ForEach-Object { Remove-Item -LiteralPath $_.FullName -Force }

Write-Output "APP BUILD PASS: $outputRoot"
Write-Output "APP LOCALES: $($supportedLocales -join ', ')"
